/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

import DAO.EstudianteDAO;
import DAO.ProfesorDAO;
import javax.swing.JOptionPane;

public class frmInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form inicioSesion
     */
    public frmInicioSesion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarioEst = new javax.swing.JTextField();
        txtContrasenniaEst = new javax.swing.JPasswordField();
        btnIngresarEst = new javax.swing.JButton();
        btnSalirEst = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioProf = new javax.swing.JTextField();
        txtContrasenniaProf = new javax.swing.JPasswordField();
        btnIngresarProf = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUsuarioAdmin = new javax.swing.JTextField();
        txtContrasenniaAdmin = new javax.swing.JPasswordField();
        btnIngresarAdmin = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 204));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jTabbedPane1.setInheritsPopupMenu(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("AR JULIAN", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BIENVENIDO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("USUARIO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("CONTRASEÑA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtUsuarioEst.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuarioEst.setForeground(new java.awt.Color(0, 51, 153));
        txtUsuarioEst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtUsuarioEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        txtContrasenniaEst.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContrasenniaEst.setForeground(new java.awt.Color(0, 51, 153));
        txtContrasenniaEst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtContrasenniaEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, -1));

        btnIngresarEst.setBackground(new java.awt.Color(0, 51, 153));
        btnIngresarEst.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIngresarEst.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (4).png"))); // NOI18N
        btnIngresarEst.setText("INGRESAR");
        btnIngresarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEstActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresarEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btnSalirEst.setBackground(new java.awt.Color(0, 51, 153));
        btnSalirEst.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalirEst.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnSalirEst.setText("SALIR");
        btnSalirEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEstActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalirEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INICIO DE SESIÓN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 410, -1));

        jLabel10.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ESTUDIANTE");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s5_logo.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jTabbedPane1.addTab("ESTUDIANTE", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BIENVENIDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("CONTRASEÑA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtUsuarioProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuarioProf.setForeground(new java.awt.Color(0, 51, 153));
        txtUsuarioProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUsuarioProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        txtContrasenniaProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContrasenniaProf.setForeground(new java.awt.Color(0, 51, 153));
        txtContrasenniaProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtContrasenniaProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, -1));

        btnIngresarProf.setBackground(new java.awt.Color(0, 51, 153));
        btnIngresarProf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIngresarProf.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (4).png"))); // NOI18N
        btnIngresarProf.setText("INGRESAR");
        btnIngresarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProfActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 51, 153));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PROFESOR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, -1));

        jLabel8.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INICIO DE SESIÓN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 410, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s5_logo.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jTabbedPane1.addTab("PROFESOR", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("AR JULIAN", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BIENVENIDO");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("USUARIO:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("CONTRASEÑA:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtUsuarioAdmin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuarioAdmin.setForeground(new java.awt.Color(0, 51, 153));
        txtUsuarioAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtUsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        txtContrasenniaAdmin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContrasenniaAdmin.setForeground(new java.awt.Color(0, 51, 153));
        txtContrasenniaAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtContrasenniaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, -1));

        btnIngresarAdmin.setBackground(new java.awt.Color(0, 51, 153));
        btnIngresarAdmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIngresarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (4).png"))); // NOI18N
        btnIngresarAdmin.setText("INGRESAR");
        btnIngresarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnIngresarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btnSalir1.setBackground(new java.awt.Color(0, 51, 153));
        btnSalir1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnSalir1.setText("SALIR");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("AR JULIAN", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ADMINISTRADOR");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 410, -1));

        jLabel17.setFont(new java.awt.Font("AR JULIAN", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("INICIO DE SESIÓN");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 410, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s5_logo.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jTabbedPane1.addTab("ADMINISTRATIVO", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProfActionPerformed
        ProfesorDAO mode = new ProfesorDAO();

        String usuario = txtUsuarioProf.getText();
        String passw = new String(txtContrasenniaProf.getPassword());

        if (usuario.equals("") || passw.equals("")) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        } else {
            mode.acceder(usuario, passw);
            dispose();
        }

    }//GEN-LAST:event_btnIngresarProfActionPerformed

    private void btnIngresarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEstActionPerformed
        EstudianteDAO modelo = new EstudianteDAO();

        String usu = txtUsuarioEst.getText();
        String pass = new String(txtContrasenniaEst.getPassword());

        if (usu.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        } else {
            modelo.acceder(usu, pass);
            dispose();
        }
    }//GEN-LAST:event_btnIngresarEstActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEstActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirEstActionPerformed

    private void btnIngresarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAdminActionPerformed

        String usu = txtUsuarioAdmin.getText();
        String pass = new String(txtContrasenniaAdmin.getPassword());

        if (usu.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        } else if (usu.equals("admin") && pass.equals("admin")) {
            frmVentanaPrincipal ventana = new frmVentanaPrincipal();
            ventana.setVisible(true);
            ventana.menuProfesor.setVisible(false);
            ventana.menuEstudiante.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Administrador NO se encuentra Registrado en el sistema\nIngrese de nuevo!", "AVISO", JOptionPane.WARNING_MESSAGE);
            txtUsuarioAdmin.setText("");
            txtContrasenniaAdmin.setText("");
        }

    }//GEN-LAST:event_btnIngresarAdminActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new inicioSesion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresarAdmin;
    public javax.swing.JButton btnIngresarEst;
    public javax.swing.JButton btnIngresarProf;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSalir1;
    public javax.swing.JButton btnSalirEst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JPasswordField txtContrasenniaAdmin;
    public javax.swing.JPasswordField txtContrasenniaEst;
    public javax.swing.JPasswordField txtContrasenniaProf;
    public javax.swing.JTextField txtUsuarioAdmin;
    public javax.swing.JTextField txtUsuarioEst;
    public javax.swing.JTextField txtUsuarioProf;
    // End of variables declaration//GEN-END:variables
}
