/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

import Vista.Estudiante.frmListarEstudiantes;
import Vista.Estudiante.frmListarProfesor;
import Vista.Estudiante.frmHorario;
import Vista.Administrador.frmEstudiante;
import Vista.Administrador.frmProfesor;
import Vista.Administrador.frmCurso;
import Controlador.InicioSesionController;
import Vista.Administrador.frmMatricula;
import Vista.Estudiante.frmListarAsistencia;
import Vista.Estudiante.frmListarNotas;
import Vista.Profesor.frmAsignarAsistencia;
import Vista.Profesor.frmAsignarNota;
import Vista.Profesor.frmMostrarAsistencia;
import Vista.Profesor.frmMostrarEstudiantes;
import Vista.Profesor.frmMostrarProfesores;

public class frmVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    private frmEstudiante estudiante;
    private frmProfesor profesor;
    private frmCurso curso;
    private frmHorario horario;
    private frmListarEstudiantes listarEstudiante;
    private frmListarProfesor listarProfesor;
    private frmAsignarNota asignarNota;
    private frmAsignarAsistencia asignarAsistencia;
    private frmMatricula matricula;
    private frmListarAsistencia listarAsistencia;
    private frmListarNotas listarNota;
    private frmMostrarEstudiantes mostrarEstudiante;
    private frmMostrarProfesores mostrarProfesores;
    private frmMostrarAsistencia mostrarAsistencia;
    private frmAcercaDe acercade;

    public frmVentanaPrincipal() {
        initComponents();
        this.setExtendedState(frmVentanaPrincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        menuEstudiante = new javax.swing.JMenu();
        verHorario = new javax.swing.JMenuItem();
        verEstClase = new javax.swing.JMenuItem();
        verProfClase = new javax.swing.JMenuItem();
        verNotas = new javax.swing.JMenuItem();
        verAsistencia = new javax.swing.JMenuItem();
        menuProfesor = new javax.swing.JMenu();
        verEstudiantes = new javax.swing.JMenuItem();
        verProfesores = new javax.swing.JMenuItem();
        ingresarNotas = new javax.swing.JMenuItem();
        ingresarAsistencia = new javax.swing.JMenuItem();
        verListaAsistencia = new javax.swing.JMenuItem();
        menuAdministrador = new javax.swing.JMenu();
        ingresarEstudiante = new javax.swing.JMenuItem();
        ingresarProfesor = new javax.swing.JMenuItem();
        ingresarCurso = new javax.swing.JMenuItem();
        ingresarMatricula = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s5_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("AR JULIAN", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA DE ADMINISTRACIÓN DE EXPEDIENTES");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TODOS LOS DERECHOS RESERVADOS © 2018");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Proyecto Final Programación 3 - Versión 3.5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 130, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        escritorio.add(jPanel1);
        jPanel1.setBounds(0, 0, 1480, 650);

        menuBar.setBackground(new java.awt.Color(0, 51, 153));
        menuBar.setBorder(null);
        menuBar.setToolTipText("");
        menuBar.setFocusTraversalPolicyProvider(true);
        menuBar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        menuBar.setInheritsPopupMenu(true);

        fileMenu.setForeground(new java.awt.Color(255, 255, 255));
        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notas.png"))); // NOI18N
        fileMenu.setText("Archivo");
        fileMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cerrarSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(0, 51, 153));
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/candado.png"))); // NOI18N
        cerrarSesion.setMnemonic('o');
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(cerrarSesion);

        salir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 51, 153));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/error.png"))); // NOI18N
        salir.setMnemonic('x');
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fileMenu.add(salir);

        menuBar.add(fileMenu);

        menuEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        menuEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lectura.png"))); // NOI18N
        menuEstudiante.setText("Estudiante");
        menuEstudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        verHorario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verHorario.setForeground(new java.awt.Color(0, 51, 153));
        verHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bloc.png"))); // NOI18N
        verHorario.setMnemonic('t');
        verHorario.setText("Ver Horario");
        verHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHorarioActionPerformed(evt);
            }
        });
        menuEstudiante.add(verHorario);

        verEstClase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verEstClase.setForeground(new java.awt.Color(0, 51, 153));
        verEstClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pensamiento (1).png"))); // NOI18N
        verEstClase.setMnemonic('y');
        verEstClase.setText("Ver Estudiantes de Clase");
        verEstClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstClaseActionPerformed(evt);
            }
        });
        menuEstudiante.add(verEstClase);

        verProfClase.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verProfClase.setForeground(new java.awt.Color(0, 51, 153));
        verProfClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conferencias.png"))); // NOI18N
        verProfClase.setMnemonic('p');
        verProfClase.setText("Ver Profesores de Clase");
        verProfClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProfClaseActionPerformed(evt);
            }
        });
        menuEstudiante.add(verProfClase);

        verNotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verNotas.setForeground(new java.awt.Color(0, 51, 153));
        verNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prueba.png"))); // NOI18N
        verNotas.setText("Ver Notas");
        verNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verNotasActionPerformed(evt);
            }
        });
        menuEstudiante.add(verNotas);

        verAsistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verAsistencia.setForeground(new java.awt.Color(0, 51, 153));
        verAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/despertador (1).png"))); // NOI18N
        verAsistencia.setText("Ver Asistencia");
        verAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAsistenciaActionPerformed(evt);
            }
        });
        menuEstudiante.add(verAsistencia);

        menuBar.add(menuEstudiante);

        menuProfesor.setForeground(new java.awt.Color(255, 255, 255));
        menuProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conferencia.png"))); // NOI18N
        menuProfesor.setText("Profesor");
        menuProfesor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        verEstudiantes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verEstudiantes.setForeground(new java.awt.Color(0, 51, 153));
        verEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pensamiento (1).png"))); // NOI18N
        verEstudiantes.setMnemonic('c');
        verEstudiantes.setText("Ver Estudiantes");
        verEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstudiantesActionPerformed(evt);
            }
        });
        menuProfesor.add(verEstudiantes);

        verProfesores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verProfesores.setForeground(new java.awt.Color(0, 51, 153));
        verProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conferencias.png"))); // NOI18N
        verProfesores.setMnemonic('a');
        verProfesores.setText("Ver Profesores");
        verProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProfesoresActionPerformed(evt);
            }
        });
        menuProfesor.add(verProfesores);

        ingresarNotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarNotas.setForeground(new java.awt.Color(0, 51, 153));
        ingresarNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prueba.png"))); // NOI18N
        ingresarNotas.setText("Ingresar / Modificar Notas");
        ingresarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarNotasActionPerformed(evt);
            }
        });
        menuProfesor.add(ingresarNotas);

        ingresarAsistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarAsistencia.setForeground(new java.awt.Color(0, 51, 153));
        ingresarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/despertador (1).png"))); // NOI18N
        ingresarAsistencia.setText("Ingresar / Modificar Asistencia");
        ingresarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarAsistenciaActionPerformed(evt);
            }
        });
        menuProfesor.add(ingresarAsistencia);

        verListaAsistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        verListaAsistencia.setForeground(new java.awt.Color(0, 51, 153));
        verListaAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        verListaAsistencia.setText("Ver Lista de Asistencia");
        verListaAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verListaAsistenciaActionPerformed(evt);
            }
        });
        menuProfesor.add(verListaAsistencia);

        menuBar.add(menuProfesor);

        menuAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        menuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj-de-arena.png"))); // NOI18N
        menuAdministrador.setText("Administrador");
        menuAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        ingresarEstudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarEstudiante.setForeground(new java.awt.Color(0, 51, 153));
        ingresarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pensamiento (1).png"))); // NOI18N
        ingresarEstudiante.setText("Ingresar Estudiante");
        ingresarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarEstudianteActionPerformed(evt);
            }
        });
        menuAdministrador.add(ingresarEstudiante);

        ingresarProfesor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarProfesor.setForeground(new java.awt.Color(0, 51, 153));
        ingresarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conferencias.png"))); // NOI18N
        ingresarProfesor.setText("Ingresar Profesor");
        ingresarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarProfesorActionPerformed(evt);
            }
        });
        menuAdministrador.add(ingresarProfesor);

        ingresarCurso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarCurso.setForeground(new java.awt.Color(0, 51, 153));
        ingresarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bloc.png"))); // NOI18N
        ingresarCurso.setText("Ingresar Curso");
        ingresarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarCursoActionPerformed(evt);
            }
        });
        menuAdministrador.add(ingresarCurso);

        ingresarMatricula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ingresarMatricula.setForeground(new java.awt.Color(0, 51, 153));
        ingresarMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ereader.png"))); // NOI18N
        ingresarMatricula.setText("Ingresar Matricula");
        ingresarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarMatriculaActionPerformed(evt);
            }
        });
        menuAdministrador.add(ingresarMatricula);

        menuBar.add(menuAdministrador);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerebro.png"))); // NOI18N
        jMenu2.setText("Información");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 51, 153));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carnet-de-identidad.png"))); // NOI18N
        jMenuItem5.setText("Acerca de...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void ingresarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarEstudianteActionPerformed
        if (estudiante == null || estudiante.isClosed()) {

            estudiante = new frmEstudiante();
            escritorio.add(estudiante);
            estudiante.show();
            estudiante.pack();
            estudiante.setLocation(25, 10);
        }
    }//GEN-LAST:event_ingresarEstudianteActionPerformed

    private void ingresarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarProfesorActionPerformed
        if (profesor == null || profesor.isClosed()) {

            profesor = new frmProfesor();
            escritorio.add(profesor);
            profesor.show();
            profesor.pack();
            profesor.setLocation(25, 10);
        }
    }//GEN-LAST:event_ingresarProfesorActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        InicioSesionController inicio = new InicioSesionController();

        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void ingresarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarCursoActionPerformed
        if (curso == null || curso.isClosed()) {
            curso = new frmCurso();
            escritorio.add(curso);
            curso.show();
            curso.pack();
            curso.setLocation(145, 0);
        }
    }//GEN-LAST:event_ingresarCursoActionPerformed

    private void verHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHorarioActionPerformed
        if (horario == null || horario.isClosed()) {
            horario = new frmHorario();
            escritorio.add(horario);
            horario.show();
            horario.pack();
            horario.setLocation(300, 0);
        }
    }//GEN-LAST:event_verHorarioActionPerformed

    private void verEstClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstClaseActionPerformed
        if (listarEstudiante == null || listarEstudiante.isClosed()) {
            listarEstudiante = new frmListarEstudiantes();
            escritorio.add(listarEstudiante);
            listarEstudiante.show();
            listarEstudiante.pack();
            listarEstudiante.setLocation(300, 0);
        }
    }//GEN-LAST:event_verEstClaseActionPerformed

    private void verProfClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProfClaseActionPerformed
        if (listarProfesor == null || listarProfesor.isClosed()) {
            listarProfesor = new frmListarProfesor();
            escritorio.add(listarProfesor);
            listarProfesor.show();
            listarProfesor.pack();
            listarProfesor.setLocation(300, 0);
        }
    }//GEN-LAST:event_verProfClaseActionPerformed

    private void ingresarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarNotasActionPerformed
        if (asignarNota == null || asignarNota.isClosed()) {
            asignarNota = new frmAsignarNota();
            escritorio.add(asignarNota);
            asignarNota.show();
            asignarNota.pack();
            asignarNota.setLocation(200, 0);
        }
    }//GEN-LAST:event_ingresarNotasActionPerformed

    private void ingresarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarAsistenciaActionPerformed
        if (asignarAsistencia == null || asignarAsistencia.isClosed()) {
            asignarAsistencia = new frmAsignarAsistencia();
            escritorio.add(asignarAsistencia);
            asignarAsistencia.show();
            asignarAsistencia.pack();
            asignarAsistencia.setLocation(200, 0);
        }
    }//GEN-LAST:event_ingresarAsistenciaActionPerformed

    private void ingresarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarMatriculaActionPerformed
        if (matricula == null || matricula.isClosed()) {
            matricula = new frmMatricula();
            escritorio.add(matricula);
            matricula.show();
            matricula.pack();
            matricula.setLocation(200, 0);
        }
    }//GEN-LAST:event_ingresarMatriculaActionPerformed

    private void verAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAsistenciaActionPerformed
        if (listarAsistencia == null || listarAsistencia.isClosed()) {
            listarAsistencia = new frmListarAsistencia();
            escritorio.add(listarAsistencia);
            listarAsistencia.show();
            listarAsistencia.pack();
            listarAsistencia.setLocation(300, 0);
        }
    }//GEN-LAST:event_verAsistenciaActionPerformed

    private void verNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verNotasActionPerformed
        if (listarNota == null || listarNota.isClosed()) {
            listarNota = new frmListarNotas();
            escritorio.add(listarNota);
            listarNota.show();
            listarNota.pack();
            listarNota.setLocation(300, 0);
        }
    }//GEN-LAST:event_verNotasActionPerformed

    private void verEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstudiantesActionPerformed
        if (mostrarEstudiante == null || mostrarEstudiante.isClosed()) {
            mostrarEstudiante = new frmMostrarEstudiantes();
            escritorio.add(mostrarEstudiante);
            mostrarEstudiante.show();
            mostrarEstudiante.pack();
            mostrarEstudiante.setLocation(250, 0);
        }
    }//GEN-LAST:event_verEstudiantesActionPerformed

    private void verProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProfesoresActionPerformed
        if (mostrarProfesores == null || mostrarProfesores.isClosed()) {
            mostrarProfesores = new frmMostrarProfesores();
            escritorio.add(mostrarProfesores);
            mostrarProfesores.show();
            mostrarProfesores.pack();
            mostrarProfesores.setLocation(250, 0);
        }
    }//GEN-LAST:event_verProfesoresActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (acercade == null || acercade.isClosed()) {
            acercade = new frmAcercaDe();
            escritorio.add(acercade);
            acercade.show();
            acercade.pack();
            acercade.setLocation(350, 0);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void verListaAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verListaAsistenciaActionPerformed
        if (mostrarAsistencia == null || mostrarAsistencia.isClosed()) {
            mostrarAsistencia = new frmMostrarAsistencia();
            escritorio.add(mostrarAsistencia);
            mostrarAsistencia.show();
            mostrarAsistencia.pack();
            mostrarAsistencia.setLocation(300, 0);
        }
    }//GEN-LAST:event_verListaAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ventanaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesion;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem ingresarAsistencia;
    private javax.swing.JMenuItem ingresarCurso;
    public javax.swing.JMenuItem ingresarEstudiante;
    private javax.swing.JMenuItem ingresarMatricula;
    private javax.swing.JMenuItem ingresarNotas;
    private javax.swing.JMenuItem ingresarProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuEstudiante;
    public javax.swing.JMenu menuProfesor;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem verAsistencia;
    private javax.swing.JMenuItem verEstClase;
    private javax.swing.JMenuItem verEstudiantes;
    private javax.swing.JMenuItem verHorario;
    private javax.swing.JMenuItem verListaAsistencia;
    private javax.swing.JMenuItem verNotas;
    private javax.swing.JMenuItem verProfClase;
    private javax.swing.JMenuItem verProfesores;
    // End of variables declaration//GEN-END:variables

}
